global:
  scrape_interval: "10s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: prometheus
    metrics_path: /
    static_configs:
      - targets:
          - "host.docker.internal:9000"
